name: ReactNative unit tests CI

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest #macos-latest

    strategy:
      matrix:
        node-version: [18.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: yarn install --frozen-lockfile
      - name: tests
        run: npm test